### PR TITLE
[REEF-915] Create tests for FailedEvaluatorHandler

### PR DESCRIPTION
**Pull request by afchung**
JIRA:
  [REEF-915](https://issues.apache.org/jira/browse/REEF-915)

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
It looks good to me and passed tests on Windows. I'll merge this.

**Comment by afchung** [comment]
@dongjoon-hyun I've just noticed that the FailedEvaluatorHandler test only tests that the event is sent to the .NET side, but it doesn't actually verify that the Driver received the FailedEvaluator Event itself. I've filed REEF-969 to address this.

**Comment by dongjoon-hyun** [comment]
Oh, I misunderstood, too. I thought that's enough to achieve the goal. Then, I'm looking forward to see PR for REEF-969 soon.

**Comment by afchung** [comment]
@dongjoon-hyun Created PR https://github.com/apache/incubator-reef/pull/653. Thanks!

**Pull request closed without merging**
