### PR TITLE
[REEF-198]  Update namespace for Clr classes

### PR DESCRIPTION
**Pull request by jwang98052**
Currently clr classes still use Microsoft.reef. as name space. This PR is to change the interfaces in Driver project to use Org.Apache.REEF.Driver.Interop. For rest of the clr class in Bridge project, replace Microsoft.Reef to Org.Apache.REEF

JIRA: REEF-198. (https://issues.apache.org/jira/browse/REEF-198)

This Closes #102  (the old PR)
This closes #      (current PR)

Author: Julia Wang  Email: jwang98052@yahoo.com

### CODE REVIEW

**Comment by markusweimer** [comment]
Are we set on the name `Interop`? In all other cases, we call it `Bridge`. Hence, this code could move to `Org.Apache.REEF.Bridge.Driver` or such.

@jwang98052 @beysims what do you think?

**Comment by jwang98052** [comment]
Currently Og.Apache.REEF.Bridge contains cpp code. 
Are you talking IInteropReturnInfo.cs and ILogger.cs? We can move them into Org.Apache.REEF.Driver.Bridge I think. They were at cpp folder previously. As they are cs files, so put them in to Org.Apache.REEF.Driver.Bridge with other bridge cs code would make more sense.

**Comment by jwang98052** [comment]
For name space used in cpp project, yes, we can also change it into Org.Apache.REEF.Bridge for consistency instead of using Interop. Good point.

**Comment by jwang98052** [comment]
Review comments addressed.

**Comment by markusweimer** [comment]
@beysims Can you test this? My VS setup is still hosed :(

**Comment by markusweimer** [comment]
This fails the same tests as the `master` branch for me. Hence, I assume it is safe to merge and proceed.

**Pull request closed without merging**
