### PR TITLE
[REEF-929] Add links to release notes to Downloads page; delete api.html

### PR DESCRIPTION
**Pull request by tcNickolas**
This change:
 * adds links to release notes for each release to Downloads page
 * deletes unreferenced page api.html

JIRA:
  [REEF-929](https://issues.apache.org/jira/browse/REEF-929)
  [REEF-920](https://issues.apache.org/jira/browse/REEF-920)

Pull request:
  This closes #

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
It looks good to me. I'll merge this.

**Comment by tcNickolas** [comment]
Could you also publish the site afterwards? I'd like to get more data points for https://issues.apache.org/jira/browse/REEF-885 - is it only my problem, or does it occur for others as well?

**Comment by dongjoon-hyun** [comment]
Oh, yes. I will do publish together. For REEF-885, I'm crossing my finger that it does not occur to me. :)
Anyway, if it occurs again, I will fix that and leave a note for you.

**Comment by dongjoon-hyun** [comment]
I finished. According to the direction, if there is no newly updated javadoc, we can ignore `apidoc`.
```
$ ./publish.sh

Shell script for uploading REEF website contents to Apache SVN!
Newly updated javadocs (if there is any) should be in the directory:
  $REEF_HOME/website/target/staging/site/apidocs/${reef.version}
Please run this script in $REEF_HOME/website.
```
So, as a test, I do not make `apidocs`. It works and looks safe for non-apidocs updates. I think you can try this someday later.
```
$REEF_HOME/website/target/staging/site/apidocs/
```

**Pull request closed without merging**
