### PR TITLE
[REEF-766] Add configurationProviders in YarnJobSubmissionClient

### PR DESCRIPTION
**Pull request by jwang98052**
Add DriverConfigurationProviders in YarnJobSubmissionClient constructor and loop through it to add the configurations to driverConfiguration.

JIRA: [REEF-766](https://issues.apache.org/jira/browse/REEF-766)

This closes #

Author: Julia Wang  Email: juliaw@apache.org

### CODE REVIEW

**Comment by markusweimer** [comment]
I'll do a pass.

**Comment by markusweimer** [comment]
@jwang98052 Looks good. Did you test it on HDI?

**Comment by markusweimer** [comment]
I'm busy all day. +1 on someone else merging after we confirmed it runs on HDI.

**Comment by afchung** [comment]
@markusweimer I'll take a pass and test on HDI.

**Comment by jwang98052** [comment]
Thanks Andrew for offering the help!

I just tested all Java REEF tests and HelloREEF with the TcpProvider configuration, all passed. 

@afchung if you can merge, that would be nice!

**Pull request closed without merging**
