### PR TITLE
[REEF-431]: Fix violations of JavadocStyle checkstyle

### PR DESCRIPTION
**Pull request by tcNickolas**
This addressed the issue by
  * fixing malformated HTML
  * converting missing Javadoc for package-info.java files to TODO: Document

JIRA: [REEF-431](https://issues.apache.org/jira/browse/REEF-431)

### CODE REVIEW

**Comment by markusweimer** [comment]
I'll merge this.

**Comment by markusweimer** [comment]
@tcNickolas Can you file a JIRA for each of the missing package level javadocs? The respective authors can then go through and fix them.

**Comment by tcNickolas** [comment]
Together with newly added package-info.java (REEF-432) there will be a hundred of package-level missing javadocs. Do we have some kind of higher-level ownership to avoid spamming JIRA that much?

**Comment by markusweimer** [comment]
Oops! Let's leave it at the module level, then.

**Pull request closed without merging**
