### PR TITLE
[REEF-624] Replace all use of DriverBridgeConfiguration with DriverConfiguration

### PR DESCRIPTION
**Pull request by tcNickolas**
This addressed the issue by
  * replacing all usages of DriverBridgeConfiguration in examples and tests
    with DriverConfiguration
  * adding IObservable<IDriverStarted> and necessary methods to test drivers

JIRA:
  [REEF-624](https://issues.apache.org/jira/browse/REEF-624)

Pull Request:
  Closes #

### CODE REVIEW

**Comment by markusweimer** [comment]
I'll test and merge

**Comment by markusweimer** [comment]
There are test failures:

`BroadcastReduceTest.TestBroadcastAndReduceOnLocalRuntime`:

```
Cleaning up test.
Org.Apache.REEF.Driver.Bridge.ClrHandlerHelper Start: 0 : 2015-08-31T17:42:23.2005420-07:00 0016
START: 2015-08-31 17:42:23 ClrHandlerHelper::CopyDllsToAppDirectory
Org.Apache.REEF.Driver.Bridge.ClrHandlerHelper Stop: 0 : 2015-08-31T17:42:23.2070308-07:00 0016
EXIT: 2015-08-31 17:42:23 ClrHandlerHelper::CopyDllsToAppDirectory. Duration: [00:00:00.0062184].
Org.Apache.REEF.Driver.Bridge.ClrHandlerHelper Start: 0 : 2015-08-31T17:42:23.2100389-07:00 0016
START: 2015-08-31 17:42:23 ClrHandlerHelper::GetAssembliesListForReefDriverApp
Org.Apache.REEF.Driver.Bridge.ClrHandlerHelper Stop: 0 : 2015-08-31T17:42:23.3015332-07:00 0016
EXIT: 2015-08-31 17:42:23 ClrHandlerHelper::GetAssembliesListForReefDriverApp. Duration: [00:00:00.0916312].
GetLogFile, driverContainerDirectory:C:\src\reef\lang\cs\TestResults\Deploy_mweimer 2015-08-31 17_42_20\Out\REEF_LOCAL_RUNTIME\ReefClrBridge-1441068147372\driver
Lines read from log file : 181
Cleaning up test.
Assert.IsTrue failed. 
   at Org.Apache.REEF.Tests.Functional.ReefFunctionalTest.ValidateSuccessForLocalRuntime(Int32 numberOfEvaluatorsToClose, String testFolder) in ReefFunctionalTest.cs: line 161
Assert.IsTrue failed. 
   at Org.Apache.REEF.Tests.Functional.ReefFunctionalTest.ValidateSuccessForLocalRuntime(Int32 numberOfEvaluatorsToClose, String testFolder) in ReefFunctionalTest.cs: line 161
Assert.IsTrue failed. 
   at Org.Apache.REEF.Tests.Functional.ReefFunctionalTest.ValidateSuccessForLocalRuntime(Int32 numberOfEvaluatorsToClose, String testFolder) in ReefFunctionalTest.cs: line 161
```

`PipelinedBroadcastReduceTest.TestPipelinedBroadcastAndReduceOnLocalRuntime`:

```
Cleaning up test.
GetLogFile, driverContainerDirectory:C:\src\reef\lang\cs\TestResults\Deploy_mweimer 2015-08-31 17_42_20\Out\REEF_LOCAL_RUNTIME\ReefClrBridge-1441068245737\driver
Lines read from log file : 183
Cleaning up test.
Assert.IsTrue failed. 
   at Org.Apache.REEF.Tests.Functional.ReefFunctionalTest.ValidateSuccessForLocalRuntime(Int32 numberOfEvaluatorsToClose, String testFolder) in ReefFunctionalTest.cs: line 161
```

`ScatterReduceTest.TestScatterAndReduceOnLocalRuntime`:

```
Cleaning up test.
GetLogFile, driverContainerDirectory:C:\src\reef\lang\cs\TestResults\Deploy_mweimer 2015-08-31 17_42_20\Out\REEF_LOCAL_RUNTIME\ReefClrBridge-1441068234174\driver
Lines read from log file : 181
Cleaning up test.
Assert.IsTrue failed. 
   at Org.Apache.REEF.Tests.Functional.ReefFunctionalTest.ValidateSuccessForLocalRuntime(Int32 numberOfEvaluatorsToClose, String testFolder) in ReefFunctionalTest.cs: line 161
```

`TestTaskMessage.TestSendTaskMessage()`:

```
Cleaning up test.
Running test edf0b053. If failed AND log uploaded is enabled, log can be find in 2015-08-31\edf0b053
GetLogFile, driverContainerDirectory:C:\src\reef\lang\cs\TestResults\Deploy_mweimer 2015-08-31 17_42_20\Out\REEF_LOCAL_RUNTIME\ReefClrBridge-1441068183300\driver
Lines read from log file : 165
Cleaning up test.
Assert.IsTrue failed. 
   at Org.Apache.REEF.Tests.Functional.ReefFunctionalTest.ValidateSuccessForLocalRuntime(Int32 numberOfEvaluatorsToClose, String testFolder) in ReefFunctionalTest.cs: line 161
Assert.IsTrue failed. 
   at Org.Apache.REEF.Tests.Functional.ReefFunctionalTest.ValidateSuccessForLocalRuntime(Int32 numberOfEvaluatorsToClose, String testFolder) in ReefFunctionalTest.cs: line 161
```

**Comment by tcNickolas** [comment]
This might be a problem with our master branch, not just with my change. I'm trying to run tests on various recent commits, and I'm getting these test failures starting with https://github.com/apache/incubator-reef/commit/e374351a957c437f29fe9b61f3cf9f703e40ee33 (and not getting them in earlier commits). Could you please double-check?

**Comment by tcNickolas** [comment]
I've fixed the tests

**Comment by markusweimer** [comment]
@tcNickolas Thanks, I will test again.

**Pull request closed without merging**
