### PR TITLE
[REEF-869] Rename IPartitionedDataset and related interfaces to IPart…

### PR DESCRIPTION
**Pull request by dkm2110**
…itionedInputDataset

This addressed the issue by
* by renaming IPartitionedDataset, IPartition and other related interfaces and interfaces to IPartitionedInputDataset, IInputPartition etc.
JIRA:
[REEF-869](https://issues.apache.org/jira/browse/REEF-869)

### CODE REVIEW

**Comment by dkm2110** [comment]
@markusweimer @jwang98052 

This is the renaming pull request.

**Comment by markusweimer** [comment]
This looks good. +1 on merging. However, I am not setup to do the testing right now. Any volunteers?

**Comment by dkm2110** [comment]
@jwang98052 @tcNickolas  Can one of you do it?

**Comment by jwang98052** [comment]
I will review and test

**Comment by jwang98052** [comment]
Looks good. I will merge it.

**Pull request closed without merging**
