### PR TITLE
[REEF-65] Remove Retained Evaluators example

### PR DESCRIPTION
**Pull request by yunseong**
This pull request removes Retained Evaluators example. The changes are

* Deleting the source code from java, cs, clr-bridge.
* Deleting the classes from reef-tests. Retained Evaluators has been used as a part of the integration tests.
* Updating the project files. (reef-examples/pom.xml, Org.Apache.REEF.Examples.csproj, etc)
* Updating `bin/run.sh`. The example command is changed from RetainedEvaluator to HelloREEF.

### CODE REVIEW

**Comment by yunseong** [comment]
@markusweimer Could you take a look? Please let me know if more changes are needed.

**Comment by markusweimer** [comment]
This looks good. I'm testing it right now.

**Comment by markusweimer** [comment]
this seems to break the REEF.NET tests. We should hold off on merging until we know why.

**Comment by yunseong** [comment]
I've rerun the tests two more times and the results are following:

* Build 260 failed at `FailDriverTest`
```
Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 95.058 sec <<< FAILURE! - in org.apache.reef.tests.fail.FailDriverTest
testFailDriverAlarm(org.apache.reef.tests.fail.FailDriverTest)  Time elapsed: 6.756 sec  <<< FAILURE!
java.lang.AssertionError: Unexpected error: java.lang.RuntimeException: org.apache.reef.exception.EvaluatorException: Evaluator [Node-1-1429968123541] is assumed to be in state [RUNNING]. But the resource manager reports it to be in state [FAILED]. This means that the Evaluator failed but wasn't able to send an error message back to the driver. Task [FailTask_FailContext_Node-1-1429968123541] was running when the Evaluator crashed.
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.reef.tests.TestUtils.assertLauncherFailure(TestUtils.java:43)
	at org.apache.reef.tests.fail.FailDriverTest.failOn(FailDriverTest.java:64)
	at org.apache.reef.tests.fail.FailDriverTest.testFailDriverAlarm(FailDriverTest.java:117)
```

* Build 261 was done without the changes from this PR by mistake.

* Build 262 failed at `FailTaskTest` and gave a different error at another place.
```
Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 89.986 sec <<< FAILURE! - in org.apache.reef.tests.fail.FailTaskTest
testFailTaskClose(org.apache.reef.tests.fail.FailTaskTest)  Time elapsed: 60.213 sec  <<< FAILURE!
java.lang.AssertionError: expected:<FAILED> but was:<FORCE_CLOSED>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.apache.reef.tests.TestUtils.assertLauncherFailure(TestUtils.java:39)
	at org.apache.reef.tests.fail.FailTaskTest.failOn(FailTaskTest.java:52)
	at org.apache.reef.tests.fail.FailTaskTest.testFailTaskClose(FailTaskTest.java:91)
```

Also, I found some cases that tests failed similarly from the history, which makes me think the failure does not have to do with this PR. @markusweimer Do you have any clue?

**Comment by markusweimer** [comment]
Unfortunately, our build servers right now only test the java side of REEF. And yes, we seem to have an issue with those tests, which sometimes fail on the Windows build server. That is probably worth looking into. My hunch is that it is a timeout that is set to strict in our tests for the HW spec of the build server.

That being said, the change here reliably breaks the REEF.NET tests. Are you setup to run those? If not, I can debug them on my end and see what happened.

**Comment by yunseong** [comment]
I'd like to do it by myself, but unfortunately I don't have the .NET
environment. Could I ask you a huge favor to debug the tests on your side?

Please let me know if there is anything I can help you.

Thank you so much.

2015년 4월 28일 (화) 오전 12:24, Markus Weimer <notifications@github.com>님이 작성:

**Comment by markusweimer** [comment]
I'll look into it.

**Comment by markusweimer** [comment]
I ran the tests again on my work machine and here they pass. It seems to have been a fluke with my setup at home. Just to be sure, @jwang98052, @beysims can you please run tests on this? If they pass for you, I'll do the merge.

**Comment by markusweimer** [comment]
@jwang98052 confirmed offline that the tests do indeed pass for her. Hence, I will merge this on the assumption that my home machine had a fluke.

**Pull request closed without merging**
