### PR TITLE
[REEF-937] Fix/Clean up YARN .NET REST client

### PR DESCRIPTION
**Pull request by anupam128**
This addressed the issue by:
 * Fix casing of property decoration in data models as YARNRM sometimes
 * silently fails on case mismatch
 * Use same library for both JSON serialization and deserialization
 * Fix unittests

JIRA:
 [REEF-937](https://issues.apache.org/jira/browse/REEF-937)

### CODE REVIEW

**Comment by afchung** [comment]
@anupam128 Please resolve the conflicts and I'll take a look. Thanks!

**Comment by anupam128** [comment]
@afchung Resolved conflicts. Thanks.

**Comment by afchung** [comment]
@anupam128 This looks good, I will test and merge tomorrow. Thanks!

**Comment by anupam128** [comment]
@afchung Rebased the changes.

**Pull request closed without merging**
