### PR TITLE
[REEF-917] Add Google Analytics on Apache REEF Websites

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR do the followings:
  * Add 'Privacy Policy' page and navigation menu for that.
  * Add a tracking javascript code in HEAD element.

JIRA:
  [REEF-917](https://issues.apache.org/jira/browse/REEF-917)

Pull request:
  This closes #

### CODE REVIEW

**Comment by jsjason** [comment]
Hi @dongjoon-hyun, you mentioned creating a new google analytics account, in JIRA. How are you planning to share that account with the other committers?

**Comment by dongjoon-hyun** [comment]
@jsjason , Absolutely! 
It's *ApacheREEF* google analytics account having 69807*** as ID. (I masked this intentionally)
But, Google Analytics works invitation-based.
I invite you. I'm sure you can access that right now.

**Comment by dongjoon-hyun** [comment]
By the way, I sent the invitation to you ( @jsjason ) , @bgchun , @dafrista , @yunseong , 
dhruv.mahajan@gmail.com , and @afchung .

**Comment by dongjoon-hyun** [comment]
@jsjason , could you log in Google Analytics?

**Comment by jsjason** [comment]
@dongjoon-hyun Yes, I can see the REEF page on my dashboard. I think you should explicitly send an email to dev telling people that they've been invited, since Google Analytics doesn't seem to send an invitation mail by itself. Also, all PMC members should be included.

**Comment by dafrista** [comment]
FYI, I *did* get an email, but sending one to the list is not a bad idea either.

**Comment by dongjoon-hyun** [comment]
Then, I will post an announce mail on @dev list.

There is one problem. The above list (7 members) is the only available Google emails I've get on Apache REEF mailing list. I need some help to setup this. 

@jsjason , could you add SNU members. :-)
@afchung , could you add MS members. :-)

All PMC members have the right to access the statistics. But, making all of PMC to get Google account to access this analytics account is beyond the scope of issue. I know that some members are reluctant to get Google account.

**Comment by dongjoon-hyun** [comment]
By the way, @jsjason  , is there any reason not to accept this PR?
I'd like to announce like this; 'You can access Apache REEF website statistics from Today'
Could you proceed this first? :-)

After merging this PR, I am going to publish websites to activate Tracking ID. As you see, there is no statistics yet. :(

**Comment by bgchun** [comment]
@dongjoon-hyun I talked with @jsjason. 
@jsjason @dongjoon-hyun I will merge it.

**Comment by dongjoon-hyun** [comment]
Thank you, @bgchun .

**Comment by jsjason** [comment]
I've added the rest of the SNU committers whose gmail accounts I know of.

2015년 11월 7일 토요일, Dongjoon Hyun<notifications@github.com>님이 작성한 메시지:

**Comment by dongjoon-hyun** [comment]
Thank you, @jsjason !

**Pull request closed without merging**
