### PR TITLE
[REEF-477]  Modify TestBridgeClient to remove the dependency on old Client code

### PR DESCRIPTION
**Pull request by jwang98052**
*This PR added test cases to test the new ClrBridgeClient and removed the tests that calls old client exe.

*It also modified ClassHierarchyGeneratingDriverStartObserver to allow  client to bind assemblies to be loaded for class hierarchy. This is to avoid to load too many unnecessary assemblies and add them into the class hierarchy.

*It disabled RealtimeLogUpload as it is not required now and causes some noises.

JIRA: REEF-477(https://issues.apache.org/jira/browse/REEF-477)

This closes #

Author: Julia Wang  Email: juliaw@apache.org

### CODE REVIEW

**Comment by jwang98052** [comment]
I removed dll reference changes to narrow down the scope. I have tested it in three enlistments and two machines, all tests are consistently passed. 
Before build, delete lang/cs/bin, lang/cs/packages and lang/cs/TestResults folder.

**Comment by jwang98052** [comment]
Please notice the branch name is REEF_477 (underscore).

**Comment by markusweimer** [comment]
I'll test this.

**Comment by markusweimer** [comment]
Oh well, now I can't build this :-(

```
Error	182	Metadata file 'D:\src\reef\lang\cs\bin\x64\Debug\Org.Apache.REEF.Examples.HelloCLRBridge\Org.Apache.REEF.Examples.HelloCLRBridge.exe' could not be found	D:\src\reef\lang\cs\Org.Apache.REEF.Tests\CSC	Org.Apache.REEF.Tests
```

**Comment by jwang98052** [comment]
It is referenced in REEF.tests project 
    <ProjectReference Include="$(SolutionDir)\Org.Apache.REEF.Examples.HelloCLRBridge\Org.Apache.REEF.Examples.HelloCLRBridge.csproj">
      <Project>{159f7d70-8acc-4d97-9f6d-2fc4ca0d8682}</Project>
      <Name>Org.Apache.REEF.Examples.HelloCLRBridge</Name>
    </ProjectReference>

After build, it should appear at .\lang\cs\bin\x64\Debug\Org.Apache.REEF.Tests

What is CSC in your test folder?

**Comment by jwang98052** [comment]
I removed all the references and re-referenced them again. Hope it helps.

**Comment by markusweimer** [comment]
@jwang98052 Thanks, I will do another test.

**Comment by markusweimer** [comment]
wohoo! Now it worked. I will merge.

**Pull request closed without merging**
