### PR TITLE
[REEF-211]  Make all csproj files default to x64

### PR DESCRIPTION
**Pull request by jwang98052**
This PR includes
Make all csproj files default to x64, remove AnyCPU
Update NuGet number to next 9
Remove a log in libLoaderto avoid null reference exception in case files is null.

JIRA: REEF-211. (https://issues.apache.org/jira/browse/REEF-211)

Author: Julia Wang  Email: jwang98052@yahoo.com

This Closes #

### CODE REVIEW

**Comment by markusweimer** [comment]
I'm looking at it now.

**Comment by markusweimer** [comment]
When building from the command line, I still get the following warnings:

```
EXEC : warning : 3 issue(s) found with package 'Org.Apache.REEF.All'. [c:\src\reef\lang\cs\Org.Apache.REEF.All\Org.Apache.REEF.All.csproj]

  Issue: Assembly outside lib folder.
  Description: The assembly 'obj\Debug\Org.Apache.REEF.All.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
  Solution: Move it into the 'lib' folder if it should be referenced.

  Issue: Assembly outside lib folder.
  Description: The assembly 'obj\x64\Debug\Org.Apache.REEF.All.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
  Solution: Move it into the 'lib' folder if it should be referenced.

  Issue: Assembly outside lib folder.
  Description: The assembly 'obj\x64\Release\Org.Apache.REEF.All.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
  Solution: Move it into the 'lib' folder if it should be referenced.
```

**Comment by markusweimer** [comment]
@jwang98052 Is that warning expected?

**Comment by jwang98052** [comment]
All the architectures have been synced in build.prop that is shared. Haven't found the root cause that caused the warning. It doesn't impact the client though.

**Comment by markusweimer** [comment]
Shall we file another issue for it then? That way we can at least merge this.

**Comment by markusweimer** [comment]
I filed [REEF-229](https://issues.apache.org/jira/browse/REEF-229) to track this and will merge this PR.

**Pull request closed without merging**
