### PR TITLE
[REEF-303] Clean up the construction of Transport implementation

### PR DESCRIPTION
**Pull request by taegeonum**
This pull request contains the followings: 
- make injectable constructor of `NettyMessagingTransport` class
- move `TransportFactory` and `MessagingTransportFactort` classes from `reef-io` to `reef-wake`
- remove `new NettyMessagingTransport` calls and change them into `TransportFactory.getInstance(..)`  

JIRA:
[REEF-303](https://issues.apache.org/jira/browse/REEF-303)

### CODE REVIEW

**Comment by markusweimer** [comment]
@bgchun Can you review this?

**Comment by markusweimer** [comment]
@bgchun ping

**Comment by bgchun** [comment]
@markusweimer I'm traveling. :)
@taegeonum Can you resolve the conflicts? I will review this pull request once you're done.

**Comment by taegeonum** [comment]
@bgchun I've resolved the conflicts.

**Comment by taegeonum** [comment]
@bgchun I've been trying to make sharable `NioEventLoopGroup` in `NettyMessagingTransport`. I will reopen the pull request after it is done.

**Pull request closed without merging**
