### PR TITLE
[REEF-602] Can't checkout Org.Apache.REEF.sln

### PR DESCRIPTION
**Pull request by dafrista**
Change file encoding to UTF-8 (no BOM)

JIRA:
  [REEF-602](https://issues.apache.org/jira/browse/REEF-602)

Pull Request:
  This closes #

### CODE REVIEW

**Comment by markusweimer** [comment]
I'll test this

**Comment by dafrista** [comment]
@markusweimer thanks!
The git diff for now says it's a binary diff because the base file is thought as binary. However, from now on this should be treated as text. For example, if you make a local change on this branch, the diff will show up as text.

**Comment by markusweimer** [comment]
VS complains about it, though:

```
Some of the properties associated with the solution could not be read.
```

**Comment by dafrista** [comment]
Ouch. I'll take another look.

**Comment by markusweimer** [comment]
The file starts with an  empty line for me, maybe that is an issue?

**Comment by dafrista** [comment]
From what I can tell, Visual Studio does not like an sln file that starts with a BOM. Git is the other way around. Sigh, you win @markusweimer I like the approach in #378 much better now :+1:

**Comment by dafrista** [comment]
Will take the approach in #378 instead

**Pull request closed without merging**
