### PR TITLE
[REEF-461]: Switch to Checkstyle 6.6

### PR DESCRIPTION
**Pull request by tcNickolas**
This addressed the issue by
  * Configuring maven-checkstyle-plugin to use custom version of checkstyle instead of default one

JIRA:
  [REEF-461](https://issues.apache.org/jira/browse/REEF-461)

### CODE REVIEW

**Comment by markusweimer** [comment]
I'll test and merge.

**Comment by markusweimer** [comment]
This doesn't pass on my machine, as there are checkstyle violations:
```
[ERROR] src\main\java\org\apache\reef\io\network\group\impl\driver\TaskNodeStatusImpl.java[156] (indentation) Indentation: 'synchronized' have incorrect indentation level 8, expected level should be 6.
[ERROR] src\main\java\org\apache\reef\io\network\group\impl\driver\TaskNodeStatusImpl.java[157] (indentation) Indentation: 'if' have incorrect indentation level 6, expected level should be 8.
[ERROR] src\main\java\org\apache\reef\io\network\group\impl\driver\TaskNodeStatusImpl.java[158] (indentation) Indentation: 'if' child have incorrect indentation level 8, expected level should be 10.
[ERROR] src\main\java\org\apache\reef\io\network\group\impl\driver\TaskNodeStatusImpl.java[158] (indentation) Indentation: 'method call' child have incorrect indentation level 8, expected level should be 10.
[ERROR] src\main\java\org\apache\reef\io\network\group\impl\driver\TaskNodeStatusImpl.java[159] (indentation) Indentation: 'if rcurly' have incorrect indentation level 6, expected level should be 8.
[ERROR] src\main\java\org\apache\reef\io\network\group\impl\driver\TaskNodeStatusImpl.java[160] (indentation) Indentation: 'method call' child have incorrect indentation level 6, expected level should be 8.
[ERROR] src\main\java\org\apache\reef\io\network\group\impl\driver\TaskNodeStatusImpl.java[160] (indentation) Indentation: 'synchronized' child have incorrect indentation level 6, expected level should be 8.
[ERROR] src\main\java\org\apache\reef\io\network\group\impl\driver\TaskNodeStatusImpl.java[161] (indentation) Indentation: 'synchronized rcurly' have incorrect indentation level 4, expected level should be 6.
```

**Comment by tcNickolas** [comment]
Indeed, looks like there was a fix in Indentation check for {{synchronized}} in 6.6. I've fixed this, now {{mvn clean install}} passes on my machine

**Comment by markusweimer** [comment]
I'll do another pass.

**Comment by markusweimer** [comment]
This looks good, I'll merge.

**Pull request closed without merging**
