### PR TITLE
 [REEF-657] Race condition in StreamingCodecFunctionCache in REEF.Network 

### PR DESCRIPTION
**Pull request by dkm2110**
This addressed the issue by
    * Making AddCodecs function threadsafe by using lock.

JIRA:
[REEF-657](https://issues.apache.org/jira/browse/REEF-657)

### CODE REVIEW

**Comment by markusweimer** [comment]
There are two commits in this, can you please squash?

Also, this adds a lock *and* the use of `ConcurrentDictionary`. Isn't that overkill?

**Comment by dkm2110** [comment]
I will squash.

So outside lock code I still access dictionary elements i.e. read them.
That's why. I will squash.

Dhruv

**Comment by dkm2110** [comment]
@markusweimer  I have done squashing.

**Comment by markusweimer** [comment]
@dkm2110 Will merge

**Pull request closed without merging**
