### PR TITLE
[REEF-118] Add Shimoga library for elastic group communication.

### PR DESCRIPTION
**Pull request by motus**
Shimoga is REEF library for elastic group communication. It provides MPI-style
operators like Broadcast and Reduce for inter-task message exchange.

JIRA: [REEF-118](https://issues.apache.org/jira/browse/REEF-118)

### CODE REVIEW

**Comment by markusweimer** [comment]
Can you please merge or rebase to current master? This state of the master this PR refers to has a build failure, hence we can't see positive Jenkins messages on here :-)

**Comment by motus** [comment]
@markusweimer Done. Could you please take another look at it? Thank you!

**Comment by bgchun** [comment]
@markusweimer @motus Is this pull request ready to be merged?

**Comment by motus** [comment]
@bgchun I am still working on it. I have to refactor lots of code due to @markusweimer comments. Give me a day or two and I will rebase a new set of changes to this branch so it looks like one coherent commit.

**Comment by motus** [comment]
@bgchun @markusweimer I think I am done with the changes. All group communication code and the corresponding unit tests are now in `reef-io`, and examples are in `nngroup` package of the `reef-examples` module. I did some major refactoring of the code and addressed all your comments.

**Comment by markusweimer** [comment]
As we discussed offline, @motus will work on moving this code into the `group` package instead of `nggroup`. The old group communications library will be deprecated and removed later.

**Comment by motus** [comment]
@bgchun I am done with the first pass - please feel free to review the code. The only major thing pending is merging `org.apache.reef.io.network.group` and `nggroup` packages - I'll work on that next week with with @shravanmn

**Comment by motus** [comment]
@bgchun @markusweimer I think I am done with the changes in response to your code review comments. Please have a look.

P.S. @shravanmn will open Jira issues regarding some outdated functionality that had been deleted from groupcomm. At least some parts of it must be re-implemented later with the new API - e.g. matrix multiplication example, scatter/gather functionality and some unit tests.

**Pull request closed without merging**
