### PR TITLE
[REEF-90]: Migrate REEF website code from a private repo to REEF repo

### PR DESCRIPTION
**Pull request by joshuaseol**
* Modified the pom.xml file of $REEF_HOME to exclude README.* files in all directories when using `mvn apache-rat:check`
 * Added a directory labelled `website` which contains the source code for the REEF website
 * Added license headers to all website/src/* files except README.md
 * Added the parent artifact and groupID and artifactID for REEF inside the website project's pom.xml file
 * The javadocs for the 0.10-incubating release needs to be created using a script which is a separate issue recorded in [REEF-91](https://issues.apache.org/jira/browse/REEF-91) and thus the javadocs link will not work until the script is created and functional.
 * The current Apache REEF logo (website/src/site/resources/REEFLogo.png) is a temporary placeholder because the real logo is under development in [REEF-14](https://issues.apache.org/jira/browse/REEF-14).

JIRA: [REEF-90](https://issues.apache.org/jira/browse/REEF-90)

### CODE REVIEW

**Comment by johnyangk** [comment]
I'll create a pointer at https://issues.apache.org/jira/browse/REEF-90 for you.

**Comment by johnyangk** [comment]
Never mind, I didn't know non-committers could also create one.

**Comment by markusweimer** [comment]
I'll merge this.

**Comment by markusweimer** [comment]
Uhm, turns our that I won't merge this :-). When I run `mvn clean site:site`, I get the following error:

```
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project  (D:\src\reef\website\pom.xml) has 1 error
[ERROR]     Non-parseable POM D:\src\reef\website\pom.xml: end tag name </version> must match start tag name <name> from line 22 (position: TEXT seen ...<name>REEF Website</version>... @22:33)  @ line 22, column 33 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
```

**Comment by markusweimer** [comment]
Nevermind, I fixed the issue on my end and will merge the fixed version.

**Pull request closed without merging**
