### PR TITLE
[REEF-1007] Disable notification emails from Travis CI build script

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR fixes the previous commit correctly.

JIRA:
  [REEF-1007](https://issues.apache.org/jira/browse/REEF-1007)

Pull Request:
  This closes #

### CODE REVIEW

**Comment by tcNickolas** [comment]
Let's wait until Jenkins build finishes, to make sure it doesn't send you notification. Then I'll merge

**Comment by dongjoon-hyun** [comment]
Yep!

**Comment by dongjoon-hyun** [comment]
So far, I didn't get any notification from `builds@travis-ci.org` after the following two builds.
https://travis-ci.org/dongjoon-hyun/incubator-reef/builds/92784745  (REEF-1007-2, 25min ago)
https://travis-ci.org/apache/incubator-reef/builds/92784880              (REEF-1007-2, 15min ago)

**Comment by tcNickolas** [comment]
I assume it didn't send notification in 2 hours, so it won't send it later. Merging

**Pull request closed without merging**
