### PR TITLE
[REEF-184] Allow NetworkService to add more than one message handlers

### PR DESCRIPTION
**Pull request by gwsshs22**
This adds new NetworkService which can register more than one message handlers
 and handle all messages through one shared transport. Also, it has asynchronous
 networking interface differ from existing NetworkService.

JIRA :
 [REEF-184] https://issues.apache.org/jira/browse/REEF-184

AUTHOR : gwsshs22 <gwsshs22@gmail.com>

### CODE REVIEW

**Comment by bgchun** [comment]
@markusweimer This pull request fails at REEF Examples on HDInsight.
@markusweimer @motus @shravanmn This pull request affects #63. 

[INFO] REEF Examples on HDInsight ........................ FAILURE [1.834s]
[INFO] Tang Test Jar A ................................... SKIPPED
[INFO] Tang Test Jar B ................................... SKIPPED
[INFO] Tang Test Jar AB .................................. SKIPPED
[INFO] Tang Test Jar B conflict A ........................ SKIPPED
[INFO] REEF Tests ........................................ SKIPPED
[INFO] REEF Website ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7:35.549s
[INFO] Finished at: Mon Mar 02 20:10:26 UTC 2015
[INFO] Final Memory: 59M/602M
[INFO] ------------------------------------------------------------------------
Waiting for Jenkins to finish collecting data
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.3:shade (default) on project reef-examples-hdinsight: Error creating shaded jar: error in opening zip file /home/jenkins/jenkins-slave/maven-repositories/1/com/sun/jersey/jersey-client/1.9/jersey-client-1.9.jar -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :reef-examples-hdinsight

**Comment by bgchun** [comment]
@shravanmn @markusweimer Can you also do code review if you have time? I can do, but it'd be good to have a fresh look at this pull request.

**Comment by markusweimer** [comment]
The error would indicate a transient issue. Can you rebuild?

**Comment by bgchun** [comment]
@gwsshs22 Could you send a well-structured note on how you changed NetworkService to dev@reef (e.g., the API changes, semantics, implementation, etc.)? This pull request's not gonna go anywhere unless we have discussion about the implications of this change.

**Comment by gwsshs22** [comment]
@bgchun Of course! I will write a concrete design documentation and send an e-mail to dev@reef with it.

**Comment by gwsshs22** [comment]
This pull request made compile error with 
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /F:/jenkins/jenkins-slave/workspace/Reef-pull-request-windows/lang/java/reef-io/src/main/java/org/apache/reef/io/network/naming/NameServer.java:[32,2] cannot find symbol
  symbol: class DefaultImplementation

 I don't have any idea why it could not find 'DefaultImplementation', which is defined in Tang. Also, this commit is successfully built in my local Mac OS X 10.9.5 machine. 

 Is there any way to rebuild this commit? Does anyone know what happened?

**Comment by dafrista** [comment]
@gwsshs22 I triggered a rebuild. Let's see what happens.

**Comment by gwsshs22** [comment]
I did not know another pull requests were merged... I will push merged commit soon.

**Comment by markusweimer** [comment]
@gwsshs22 @bgchun Can you please post the design description to the JIRA? That is much easier to find once this is merged in than the mailing list discussion :-)

**Comment by gwsshs22** [comment]
@markusweimer I will post the description soon, thank you :)

**Comment by bgchun** [comment]
@gwsshs22 There's repetitive code, which needs to be DRYed out. Also there are missing comments and headers. Class names are not well chosen. I can't merge this code. 

I will send you more comments later.

**Comment by markusweimer** [comment]
Is this still being actively reviewed / worked on?

**Comment by bgchun** [comment]
@markusweimer @taegeonum is working on it. We need a cleaner way to share a network transport.

**Comment by markusweimer** [comment]
If the PR isn't ready to be reviewed, can we close it until it is?

**Comment by bgchun** [comment]
Sounds fine by me.


On Thu, May 21, 2015 at 5:50 AM, Markus Weimer <notifications@github.com>
wrote:

> If the PR isn't ready to be reviewed, can we close it until it is?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-reef/pull/97#issuecomment-104121712>.
>



-- 
Byung-Gon Chun

**Comment by gwsshs22** [comment]
I am working on this issue with @taegeonum to clean up. We will make another PR after works done.

**Pull request closed without merging**
