### PR TITLE
[REEF-585] Add Mariia to committers list on website

### PR DESCRIPTION
**Pull request by dafrista**
Add Maria, and fix a typo on team page.

JIRA:
  [REEF-585](https://issues.apache.org/jira/browse/REEF-585)

Pull Request:
  This closes #

### CODE REVIEW

**Comment by tcNickolas** [comment]
I will merge

**Comment by markusweimer** [comment]
@tcNickolas Ironically, you might not be able to. Do you have write-access to the GIT and SVN repos yet? The site needs to be published into the SVN repo.

**Comment by tcNickolas** [comment]
This change doesn't look like the one which actually grants the access. So I should be able to merge it once I have the access (which I need to check, I haven't tried yet). So it's a perfect change to confirm that I have access to both

**Comment by markusweimer** [comment]
@tcNickolas OK, makes sense.

**Comment by tcNickolas** [comment]
I'm trying to generate the site and see the change, and it fails. I've done
`git branch -b REEF-585`
`git pull apache master`
`git pull https://github.com/dafrista/incubator-reef REEF-585`
`mvn clean site:site`

The last step fails 
`[WARNING] Unable to create Maven project for org.apache.reef:tang:pom:0.13.0-incubating-SNAPSHOT from repository.`
`org.apache.maven.project.ProjectBuildingException: Error resolving project artifact: Failure to find org.apache.reef:tang:pom:0.13.0-incubating-SNAPSHOT in http://repository.apache.org/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced for project org.apache.reef:tang:pom:0.13.0-incubating-SNAPSHOT`

I've tried doing `mvn clean site:site` for code from apache/incubator-reef, and it fails with the same error. @dafrista Does `mvn clean site:site` work for you for this change?

**Comment by dafrista** [comment]
@tcNickolas I do see the warning, but the page in question is updated successfully. Did you run `mvn clean site:site` from `website/`? Then you should find the updated page at `./target/staging/site/team.html`.

**Comment by jsjason** [comment]
Hi, the warning @tcNickolas posted is probably because of the lines 
```
<dependency>
    <groupId>${project.groupId}</groupId>
    <artifactId>tang</artifactId>
    <version>${project.version}</version>
</dependency>

<dependency>
    <groupId>${project.groupId}</groupId>
    <artifactId>wake</artifactId>
    <version>${project.version}</version>
</dependency>

<dependency>
    <groupId>${project.groupId}</groupId>
    <artifactId>test-jar</artifactId>
    <version>${project.version}</version>
    <classifier>tests</classifier>
</dependency>
```
in $REEF_HOME/pom.xml (around line 374). They don't break the build, though.

**Comment by jsjason** [comment]
The "build" I just said refers to the website generation, not the project build.

**Comment by tcNickolas** [comment]
My bad, was looking for the updated pages in the wrong `site` folder (`website/target/site/` one). The change looks good. 

What is the next step - publish the site first, commit to git second? And what is our guideline for log message for svn - REEF issue # and JIRA title, like in http://svn.apache.org/viewvc?view=revision&revision=1695227 ?

**Comment by dafrista** [comment]
AFAIK, we don't have a policy for either.
What I've done personally is commit to git first, publish site second. For the log message, the SVN log will be seen by all incubator projects, so clearly denote that this is a REEF related change.

**Pull request closed without merging**
