### PR TITLE
[REEF-980] Remove deprecated LocalAddressProviderFactory and related code

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
JIRA:
  [REEF-980](https://issues.apache.org/jira/browse/REEF-980)

Pull Request:
  This closes #

### CODE REVIEW

**Comment by afchung** [comment]
I'll take a look at this.

**Comment by dongjoon-hyun** [comment]
Thank you, @afchung .

**Comment by afchung** [comment]
Looks good. Do we have a TODO item associated with removing the ``LocalAddressProviderFactory``? When was it deprecated?

**Comment by afchung** [comment]
Tagging @tcNickolas to see if she knows anything about the deprecation of this class.

**Comment by dongjoon-hyun** [comment]
When I searched, it's in https://issues.apache.org/jira/browse/REEF-552 . (Since 0.11)
And, I'm working on removing all Wake deprecated logs before next release.

**Comment by tcNickolas** [comment]
I was just going to write that :-) It's been deprecated since 0.11, and it's great to see a volunteer to handle it!

**Comment by afchung** [comment]
Sounds good, I'll test and merge this PR then. Are we going to allow for another release before removing the class?

**Comment by tcNickolas** [comment]
We can delete it as soon as all references to it are removed from our code. If we mark class as deprecated in release X, we can delete it in release X+1. If we delete it now, it will be part of 0.14, which is more than 1 release later than 0.11

**Comment by dongjoon-hyun** [comment]
Oh, this PR is just deleting the usage of `LocalAddressProviderFactory` to remove maven build warnings.

**Comment by dongjoon-hyun** [comment]
Do you mean delete `LocalAddressProviderFactory` itself?

**Comment by afchung** [comment]
Yes. I was wondering since we didn't specify a deprecation version in the JavaDocs previously.

**Comment by dongjoon-hyun** [comment]
As @tcNickolas mentioned, I think we can delete `LocalAddressProviderFactory`, too.
Am I right?

**Comment by tcNickolas** [comment]
I see after this PR there is still one use of LocalAddressProviderFactory, in NameServerImpl. Could you fix that too, and delete the class?

**Comment by afchung** [comment]
@dongjoon-hyun In that case, it would be great if you can modify the JIRA item and commit comments accordingly. I'll test and merge after that. Thanks!

**Comment by dongjoon-hyun** [comment]
@afchung and @tcNickolas . I can do that. Thank you for improving this PR. I will update from JIRA.

**Comment by dongjoon-hyun** [comment]
I'm ready to review again, @afchung .

**Comment by dongjoon-hyun** [comment]
Thank you all.

**Pull request closed without merging**
