### PR TITLE
[REEF-872] Add Dhruv to the REEF committer list on website

### PR DESCRIPTION
**Pull request by dkm2110**
This addressed the issue by
* adding dhruv to the website

JIRA:
[REEF-872](https://issues.apache.org/jira/browse/REEF-872)

### CODE REVIEW

**Comment by dkm2110** [comment]
@jwang98052 @tcNickolas 
Can one of you merge this one?

**Comment by dongjoon-hyun** [comment]
Hi, @dkm2110 . If you don't mind, I will merge this for you.

**Comment by dkm2110** [comment]
Sure

**Comment by dongjoon-hyun** [comment]
Yep. It's done now, @dkm2110 .

**Pull request closed without merging**
