### PR TITLE
[REEF-695] Reorganize reef-examples/scheduler classes into packages

### PR DESCRIPTION
**Pull request by dafrista**
Move classes into client and driver packages.
Task classes are in a separate package, o.a.r.examples.library.

JIRA:
  [REEF-695](https://issues.apache.org/jira/browse/REEF-695)

Pull Request:
  Closes #

### CODE REVIEW

**Comment by yunseong** [comment]
Thanks for the cleanup! The code is more readable now. I've read the changes and they look good to me. Does anybody have comments?

**Comment by markusweimer** [comment]
Looks good to me.

**Comment by bgchun** [comment]
Looks good.

**Comment by yunseong** [comment]
Thanks, I'm merging it.

**Pull request closed without merging**
