### PR TITLE
[REEF-304]: Cache loaded ClassHierarchy in ActiveContextBridge

### PR DESCRIPTION
**Pull request by afchung**
This addressed the issue by
  * Only loading Class Hierarchy once in the constructor

JIRA: [REEF-304](https://issues.apache.org/jira/browse/REEF-304)

### CODE REVIEW

**Comment by jwang98052** [comment]
I will look at it.

**Comment by jwang98052** [comment]
Put the PR link in REEF-304

**Comment by jwang98052** [comment]
You can push to Microsoft-CISL instead of your forked repository next time

**Comment by afchung** [comment]
I don't think I have access to Microsoft-CISL.

**Comment by markusweimer** [comment]
This looks like an improvement to me, thanks! After testing, this can go in as-is.

However, on REEF-304, I think we can do better still. The code as is still has an an justified memory usage of O(#contexts), as we load the *same* class hierarchy for the CLR for every context.

@jwang98052 @beysims: Do we actually modify the class hierarchy once loaded? If not, we probably should load it once, preferably in a Tang-managed object or via an external constructor.

**Comment by markusweimer** [comment]
I'll test and merge this in the meantime.

**Comment by markusweimer** [comment]
I filled [REEF-310](https://issues.apache.org/jira/browse/REEF-310) for the overall issue.

**Comment by jwang98052** [comment]
For the same tasks, class hierarchy are the same. Unless the clients submit context every time for different tasks. Even in that case, most cases, clients would put all the task dlls in the class hierarchy at once. So load it once at java side make sense. 
I also tested it last night in .Net. The change looks good.

**Pull request closed without merging**
