### PR TITLE
[REEF-858] Enable StyleCop.CSharp.MaintainabilityRules and fix violation

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
Since REEF-979 enforces StyleCop during build phase, this PR has the patch
enabling StyleCop.CSharp.MaintainablilityRules and fixing violations.

JIRA:
  [REEF-858](https://issues.apache.org/jira/browse/REEF-858)

Pull Request:
  This closes #

### CODE REVIEW

**Comment by tcNickolas** [comment]
I suspect this PR will have to be updated after https://github.com/apache/incubator-reef/pull/660 is merged. JIRA mentions violations of FileMayOnlyContainASingleClass rule in Wake, but this change enables this rule while not fixing or ignoring those violations.

**Comment by dongjoon-hyun** [comment]
Hmm. You're right. I thought I intentionally leave the rule as a false. But, it's not. After #660 , I will update this PR again.

**Comment by tcNickolas** [comment]
I've checked this PR with #660 merged in, and it produces 399 CSharp.Maintainability violations.

**Comment by tcNickolas** [comment]
Looks good, I'll merge

**Comment by dongjoon-hyun** [comment]
Thank you, @tcNickolas .

**Pull request closed without merging**
