### PR TITLE
[REEF-114] Trigger .Net build from Maven build

### PR DESCRIPTION
**Pull request by jwang98052**
[REEF-114] Trigger .Net build from Maven build

 Add pom file for cs project
 Drop driver.dll to the folder for reef-bridge-clr to consume at build time
 Remove driver.dll from repository as it can be generated on the fly
 set dependency between reef-bridge-clr and cs project

To build entire project with .Net code, -PDotNet need to be added with the mvn command.
 mvn clean install -PDotNet -PBridge

JIRA: Reef-114. (https://issues.apache.org/jira/browse/REEF-114)
JIRA: REEF-17 ( https://issues.apache.org/jira/browse/REEF-17)

Author: Julia Wang Email: jwang98052@yahoo.com

### CODE REVIEW

**Comment by markusweimer** [comment]
-1 on formal grounds: The first line of the commit message doesn't contain the JIRA.

**Comment by markusweimer** [comment]
I'll try this.

**Comment by markusweimer** [comment]
I get a build failure when running `mvn -DskipTests -PDotNET -PBridge clean install`:

```
[INFO] Compiling 40 source files to C:\src\reef\lang\java\reef-tests\target\classes
[INFO] Compiling 7 source files to C:\src\reef\lang\java\reef-examples-clr\target\classes
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(347,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\src\reef\lang\cpp\reef-bridge-clr\src\main\Cpp\CppBridge\JavaClrBridge\JavaClrBridge.vcxproj]
Done Building Project "C:\src\reef\lang\cpp\reef-bridge-clr\src\main\Cpp\CppBridge\JavaClrBridge\JavaClrBridge.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\src\reef\lang\cpp\reef-bridge-clr\src\main\Cpp\CppBridge\JavaClrBridge\JavaClrBridge.vcxproj.metaproj" (default targets) -- FAILED.
Done Building Project "C:\src\reef\lang\cpp\reef-bridge-clr\src\main\Cpp\CppBridge\JavaClrBridge\JavaClrBridge.sln" (default targets) -- FAILED.

Build FAILED.
```

**Comment by jwang98052** [comment]
Addressd NuGet loading issue during the build.

**Comment by markusweimer** [comment]
I got a little further now, but the build still fails:

```
 C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:"..\..\..\..\..\target\classes\JavaClrBridge.dll" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:"D:\src\reef\lang\cpp\reef-bridge-clr\src\main\Cpp\CppBridge\JavaClrBridge\x64\Release\JavaClrBridge.pdb" /TLBID:1 /DYNAMICBASE /FIXED:NO /NXCOMPAT /MACHINE:X64 /DLL x64\Release\ActiveContextClr2Java.obj
  x64\Release\AllocatedEvaluatorClr2Java.obj
  x64\Release\AssemblyInfo.obj
  x64\Release\AssemblyUtil.obj
  x64\Release\BinaryUtil.obj
  x64\Release\ClosedContextClr2Java.obj
  x64\Release\CommonUtilities.obj
  x64\Release\CompletedEvaluatorClr2Java.obj
  x64\Release\CompletedTaskClr2Java.obj
  x64\Release\ContextMessageClr2Java.obj
  x64\Release\EvaluatorRequestorClr2Java.obj
  x64\Release\FailedContextClr2Java.obj
  x64\Release\FailedEvaluatorClr2Java.obj
  x64\Release\FailedTaskClr2Java.obj
  x64\Release\HttpServerClr2Java.obj
  x64\Release\InteropLogger.obj
  x64\Release\InteropReturnInfo.obj
  x64\Release\InteropUtil.obj
  x64\Release\JavaClrBridge.obj
  x64\Release\RunningTaskClr2Java.obj
  x64\Release\SuspendedTaskClr2Java.obj
  x64\Release\TaskMessageClr2Java.obj
  "x64\Release\.NETFramework,Version=v4.5.AssemblyAttributes.obj"
LINK : fatal error LNK1181: cannot open input file 'gdi32.lib' [D:\src\reef\lang\cpp\reef-bridge-clr\src\main\Cpp\CppBridge\JavaClrBridge\JavaClrBridge.vcxproj]
Done Building Project "D:\src\reef\lang\cpp\reef-bridge-clr\src\main\Cpp\CppBridge\JavaClrBridge\JavaClrBridge.vcxproj" (default targets) -- FAILED.
Done Building Project "D:\src\reef\lang\cpp\reef-bridge-clr\src\main\Cpp\CppBridge\JavaClrBridge\JavaClrBridge.vcxproj.metaproj" (default targets) -- FAILED.
Done Building Project "D:\src\reef\lang\cpp\reef-bridge-clr\src\main\Cpp\CppBridge\JavaClrBridge\JavaClrBridge.sln" (default targets) -- FAILED.
```

This is confusing on two levels for me:

  1. It uses Visual Studio 11.0 tools. Aren't we using VS 2013, also known as VS 12?
  2. It complains about gdi? How come we even use that?

**Comment by jwang98052** [comment]
Updated cpp sln and project to VS 2013 and changed ToolsVersion="12.0" . Change has been pushed in.

**Comment by markusweimer** [comment]
The most recent changes worked, if I follow the [build instructions](https://cwiki.apache.org/confluence/display/REEF/Compiling+REEF). I will merge this.

**Pull request closed without merging**
