### PR TITLE
[REEF-894] GetBridgeInjector should not create a new Injector

### PR DESCRIPTION
**Pull request by afchung**
This addressed the issue by
  * Make BridgeInjector and BridgeConfiguration static lazy.

JIRA:
  [REEF-894](https://issues.apache.org/jira/browse/REEF-894)

### CODE REVIEW

**Comment by afchung** [comment]
It would appear that some tests are unstable with this PR, I'll take a closer look...

**Comment by afchung** [comment]
Can the reviewer pull and run tests on Local? I don't believe my changes should affect the tests that are run in the Jenkins environment. Thanks!

**Comment by dongjoon-hyun** [comment]
@afchung , I tested and it passed, too.

**Comment by afchung** [comment]
Thanks @dongjoon-hyun!

**Pull request closed without merging**
