### PR TITLE
Change Bridge namespace to comply with naming convention

### PR DESCRIPTION
**Pull request by yingdachen**
Change Bridge namespace naming convention

JIRA :
[REEF-198] https://issues.apache.org/jira/browse/REEF-198

AUTHOR : yingdachen@apache.org

### CODE REVIEW

**Comment by markusweimer** [comment]
@yingdachen Can you please squash this into a single commit against master?

**Comment by yingdachen** [comment]
@markusweimer will do.

**Comment by markusweimer** [comment]
You might want to wait till #103 is merged, though.

**Comment by jwang98052** [comment]
#103 is closed. Please go ahead to merge and squash.

**Comment by yingdachen** [comment]
@markusweimer @motus ahhh...looks like it is trickier to squash when a pull request is already out, this is quite messed up, anyway to do it over?

**Comment by markusweimer** [comment]
you can force-push into this branch. It should reset it.

**Comment by jwang98052** [comment]
Still need to squash first and resolve all conflicts, then force push

**Comment by markusweimer** [comment]
@yingdachen This has been overrun by recent changes, it seems :-) Can you close the PR as I *believe* the issue is already addressed.

**Comment by yingdachen** [comment]
Markus,

I am currently on a business trip in Beijing (for another two weeks), and
for some weird reason I cannot get access to Git (even Gmail is a fight to
finally get into...), could you, or Julia, close this for me?

Thanks,
-Yingda

**Comment by markusweimer** [comment]
@yingdachen, we don't have admin access to the Apache git account. Hence, we cannot close this PR, only you can. We'll just let it sit here till you are back. Safe travels :-)

**Comment by yingdachen** [comment]
just came back and saw this has been taken care of, thanks julia

**Pull request closed without merging**
