### PR TITLE
[REEF-37] Use MaxNumberOfEvaluators in place of the previous confusing names for the class NumberOfProcesses

### PR DESCRIPTION
**Pull request by johnyangk**
Change the class name from NumberOfProcesses to MaxNumberOfEvaluators
Change related static global variables' names to MaxNumberOfEvaluators as well

JIRA:
  [REEF-37] https://issues.apache.org/jira/browse/REEF-37

### CODE REVIEW

**Comment by markusweimer** [comment]
Would it be a good idea to replace "Container" with "Evaluator"? If I recall correctly, the container used for the Driver isn't counted against this max.

**Comment by markusweimer** [comment]
@johnyangk Also, please post a link to here on the JIRA.

**Comment by johnyangk** [comment]
@markusweimer 
Agreed. Changed Container -> Evaluator. Also posted the link as a comment on JIRA in addition to the issue link.

**Comment by markusweimer** [comment]
@johnyangk I get merge conflicts when I try to merge this. Can you have a look?

**Comment by johnyangk** [comment]
@markusweimer Sure, I'll take a look.

**Comment by johnyangk** [comment]
@markusweimer I resolved the conflicts.

**Comment by markusweimer** [comment]
I'm working on this now.

**Pull request closed without merging**
