### PR TITLE
[REEF-577] Implement IMRU Driver, Client, End to End MapperCount and Broadcast Reduce Examples

### PR DESCRIPTION
**Pull request by dkm2110**
[REEF-577] Implement IMRU Driver, Client, End to End MapperCount and Broadcast Reduce Examples

This addressed the issue by
  * implementing REEF IMRU Driver that actually runs Map and Update tasks given the job definition given by user.

  * implementing REEF IMRU Client

  * creating end to end mapper count example running on reef

  * creating end to end  IMRU Broadcast and Reduce example with integer array that tests most of IMRU aspects except partitioned datasets

  * introducing a StreamingCodecConfigurationMinusMessage configuration module in REEF.Network.Group.Config that gives internal codec configurations used within group communication to the external applications like IMRU.

JIRA:
  [REEF-577](https://issues.apache.org/jira/browse/REEF-577)

### CODE REVIEW

**Comment by dkm2110** [comment]
@markusweimer @jwang98052 

Please find the new pull request. This has everything now including client driver and two examples

**Comment by markusweimer** [comment]
I suggest to do this in steps. The first would be to create the new empty projects. Writing msbuild files has proven to be challenging several times, so it is worthwhile reviewing that in isolation. Also, it would allow us to merge the usually conflict-inducing changes to the .sln file early on to avoid later blockage.

**Comment by dkm2110** [comment]
OK. Lemme file following jiras

Driver plus client
Create empty imru.examples project
Introduce mapper count in imru. Examples
Introduce broadcast and reduce

**Comment by markusweimer** [comment]
@dkm2110 Excellent plan!

**Comment by markusweimer** [comment]
@dkm2110 This is replaced by #385 and subsequent PRs, right? If so, please close this PR.

**Comment by dkm2110** [comment]
This one is replaced by #385

**Comment by dkm2110** [comment]
done

**Pull request closed without merging**
