### PR TITLE
[REEF-160] Fast-fail when protoc version differs from protobuf

### PR DESCRIPTION
**Pull request by dafrista**
Add protoc version check to root pom.

JIRA: [REEF-160] https://issues.apache.org/jira/browse/REEF-160

### CODE REVIEW

**Comment by markusweimer** [comment]
I will test and merge this

**Comment by markusweimer** [comment]
I confirmed this works on Windows.

**Comment by jwang98052** [comment]
This PR caused build failed. 

At root level, build with command line:

mvn clean install -PDotNet -PBridge -DskipTests

It causes \lang\cpp\reef-bridge-clr\src\main\Cpp\CppBridge\JavaClrBridge\JavaClrBridge.sln build failed

**Comment by markusweimer** [comment]
@jwang98052 Please file this as a JIRA such that we can track it.

**Pull request closed without merging**
