### PR TITLE
[REEF-602] Treat .sln files as binary

### PR DESCRIPTION
**Pull request by markusweimer**
JIRA:
  [REEF-602](https://issues.apache.org/jira/browse/REEF-602)

### CODE REVIEW

**Comment by markusweimer** [comment]
Don't merge this yet, REEF-602 hasn't converged yet.

**Comment by markusweimer** [comment]
Replaced by #379

**Comment by markusweimer** [comment]
#379 did not conclude, reopening.

**Comment by dafrista** [comment]
I've tested. I'll merge.

**Pull request closed without merging**
